# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

language: r
r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

env:
- TZ=Europe/Vienna
- TZ=Europe/London
- TZ=US/Pacific
- TZ=Etc/UTC

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

